#' Human Regulator sets as Gene Names
#' 
#' Human regulator sets generated by the Califano lab for use with ARACNe3 and NaRnEA.
#' Regulators are separated into TFs, COTFs, Singaling, and Surface proteins.
#' Stored as a list of lists.
#' 
#' @docType data
#' 
#' @usage data(human_regulators)
#' 
#' @format A list with four elements; each a list for a class of regulators.
#' 
#' @source Curated by the Califano lab. See ARACNe3 for more details.
#' 
#' @examples 
#' data(human_regulators)
#' \donttest{length(human_regulators)}
"human_regulators"