#' Mouse Regulator sets as Gene Names
#' 
#' Mouse regulator sets generated by the Califano lab for use with ARACNe3 and NaRnEA.
#' Regulators are separated into TFs, COTFs, and Surface proteins.
#' Stored as a list of lists.
#' 
#' @docType data
#' 
#' @usage data(mouse_regulators)
#' 
#' @format A list with three elements; each a list for a class of regulators.
#' 
#' @source Curated by the Califano lab. See ARACNe3 for more details.
#' 
#' @examples 
#' data(mouse_regulators)
#' \donttest{length(mouse_regulators)}
"mouse_regulators"